*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 2019-07-31 at 11:56:31
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZPARTNER05......................................*
FORM GET_DATA_ZPARTNER05.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM SBUSPART WHERE
(VIM_WHERETAB) .
    CLEAR ZPARTNER05 .
ZPARTNER05-MANDANT =
SBUSPART-MANDANT .
ZPARTNER05-BUSPARTNUM =
SBUSPART-BUSPARTNUM .
ZPARTNER05-CONTACT =
SBUSPART-CONTACT .
ZPARTNER05-CONTPHONO =
SBUSPART-CONTPHONO .
ZPARTNER05-BUSPATYP =
SBUSPART-BUSPATYP .
    SELECT SINGLE * FROM STRAVELAG WHERE
AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC EQ 0.
ZPARTNER05-MANDT =
STRAVELAG-MANDT .
ZPARTNER05-AGENCYNUM =
STRAVELAG-AGENCYNUM .
ZPARTNER05-NAME =
STRAVELAG-NAME .
ZPARTNER05-STREET =
STRAVELAG-STREET .
ZPARTNER05-POSTBOX =
STRAVELAG-POSTBOX .
ZPARTNER05-POSTCODE =
STRAVELAG-POSTCODE .
ZPARTNER05-CITY =
STRAVELAG-CITY .
ZPARTNER05-COUNTRY =
STRAVELAG-COUNTRY .
ZPARTNER05-REGION =
STRAVELAG-REGION .
ZPARTNER05-TELEPHONE =
STRAVELAG-TELEPHONE .
ZPARTNER05-URL =
STRAVELAG-URL .
ZPARTNER05-LANGU =
STRAVELAG-LANGU .
ZPARTNER05-CURRENCY =
STRAVELAG-CURRENCY .
    ENDIF.
<VIM_TOTAL_STRUC> = ZPARTNER05.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZPARTNER05 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZPARTNER05.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZPARTNER05-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM SBUSPART WHERE
  BUSPARTNUM = ZPARTNER05-BUSPARTNUM .
    IF SY-SUBRC = 0.
    DELETE SBUSPART .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM STRAVELAG WHERE
    AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC = 0.
    DELETE STRAVELAG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM SBUSPART WHERE
  BUSPARTNUM = ZPARTNER05-BUSPARTNUM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR SBUSPART.
    ENDIF.
SBUSPART-MANDANT =
ZPARTNER05-MANDANT .
SBUSPART-BUSPARTNUM =
ZPARTNER05-BUSPARTNUM .
SBUSPART-CONTACT =
ZPARTNER05-CONTACT .
SBUSPART-CONTPHONO =
ZPARTNER05-CONTPHONO .
SBUSPART-BUSPATYP =
ZPARTNER05-BUSPATYP .
    IF SY-SUBRC = 0.
    UPDATE SBUSPART ##WARN_OK.
    ELSE.
    INSERT SBUSPART .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM STRAVELAG WHERE
    AGENCYNUM = SBUSPART-BUSPARTNUM .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR STRAVELAG.
STRAVELAG-AGENCYNUM =
SBUSPART-BUSPARTNUM .
      ENDIF.
STRAVELAG-MANDT =
ZPARTNER05-MANDT .
STRAVELAG-AGENCYNUM =
ZPARTNER05-AGENCYNUM .
STRAVELAG-NAME =
ZPARTNER05-NAME .
STRAVELAG-STREET =
ZPARTNER05-STREET .
STRAVELAG-POSTBOX =
ZPARTNER05-POSTBOX .
STRAVELAG-POSTCODE =
ZPARTNER05-POSTCODE .
STRAVELAG-CITY =
ZPARTNER05-CITY .
STRAVELAG-COUNTRY =
ZPARTNER05-COUNTRY .
STRAVELAG-REGION =
ZPARTNER05-REGION .
STRAVELAG-TELEPHONE =
ZPARTNER05-TELEPHONE .
STRAVELAG-URL =
ZPARTNER05-URL .
STRAVELAG-LANGU =
ZPARTNER05-LANGU .
STRAVELAG-CURRENCY =
ZPARTNER05-CURRENCY .
    IF SY-SUBRC = 0.
    UPDATE STRAVELAG ##WARN_OK.
    ELSE.
    INSERT STRAVELAG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZPARTNER05-UPD_FLAG,
STATUS_ZPARTNER05-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZPARTNER05.
  SELECT SINGLE * FROM SBUSPART WHERE
BUSPARTNUM = ZPARTNER05-BUSPARTNUM .
ZPARTNER05-MANDANT =
SBUSPART-MANDANT .
ZPARTNER05-BUSPARTNUM =
SBUSPART-BUSPARTNUM .
ZPARTNER05-CONTACT =
SBUSPART-CONTACT .
ZPARTNER05-CONTPHONO =
SBUSPART-CONTPHONO .
ZPARTNER05-BUSPATYP =
SBUSPART-BUSPATYP .
    SELECT SINGLE * FROM STRAVELAG WHERE
AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC EQ 0.
ZPARTNER05-MANDT =
STRAVELAG-MANDT .
ZPARTNER05-AGENCYNUM =
STRAVELAG-AGENCYNUM .
ZPARTNER05-NAME =
STRAVELAG-NAME .
ZPARTNER05-STREET =
STRAVELAG-STREET .
ZPARTNER05-POSTBOX =
STRAVELAG-POSTBOX .
ZPARTNER05-POSTCODE =
STRAVELAG-POSTCODE .
ZPARTNER05-CITY =
STRAVELAG-CITY .
ZPARTNER05-COUNTRY =
STRAVELAG-COUNTRY .
ZPARTNER05-REGION =
STRAVELAG-REGION .
ZPARTNER05-TELEPHONE =
STRAVELAG-TELEPHONE .
ZPARTNER05-URL =
STRAVELAG-URL .
ZPARTNER05-LANGU =
STRAVELAG-LANGU .
ZPARTNER05-CURRENCY =
STRAVELAG-CURRENCY .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZPARTNER05-MANDT .
      CLEAR ZPARTNER05-AGENCYNUM .
      CLEAR ZPARTNER05-NAME .
      CLEAR ZPARTNER05-STREET .
      CLEAR ZPARTNER05-POSTBOX .
      CLEAR ZPARTNER05-POSTCODE .
      CLEAR ZPARTNER05-CITY .
      CLEAR ZPARTNER05-COUNTRY .
      CLEAR ZPARTNER05-REGION .
      CLEAR ZPARTNER05-TELEPHONE .
      CLEAR ZPARTNER05-URL .
      CLEAR ZPARTNER05-LANGU .
      CLEAR ZPARTNER05-CURRENCY .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZPARTNER05 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZPARTNER05-BUSPARTNUM TO
SBUSPART-BUSPARTNUM .
MOVE ZPARTNER05-MANDANT TO
SBUSPART-MANDANT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SBUSPART'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SBUSPART TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SBUSPART'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE SBUSPART-BUSPARTNUM TO
STRAVELAG-AGENCYNUM .
MOVE ZPARTNER05-MANDANT TO
STRAVELAG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'STRAVELAG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN STRAVELAG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'STRAVELAG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVSCARR_05M.....................................*
FORM GET_DATA_ZVSCARR_05M.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSCARR_05 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSCARR_05M .
ZVSCARR_05M-MANDT =
ZTSCARR_05-MANDT .
ZVSCARR_05M-CARRID =
ZTSCARR_05-CARRID .
ZVSCARR_05M-CARRNAME =
ZTSCARR_05-CARRNAME .
ZVSCARR_05M-CURRCODE =
ZTSCARR_05-CURRCODE .
ZVSCARR_05M-URL =
ZTSCARR_05-URL .
<VIM_TOTAL_STRUC> = ZVSCARR_05M.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSCARR_05M .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSCARR_05M.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSCARR_05M-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSCARR_05 WHERE
  CARRID = ZVSCARR_05M-CARRID .
    IF SY-SUBRC = 0.
    DELETE ZTSCARR_05 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSCARR_05 WHERE
  CARRID = ZVSCARR_05M-CARRID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSCARR_05.
    ENDIF.
ZTSCARR_05-MANDT =
ZVSCARR_05M-MANDT .
ZTSCARR_05-CARRID =
ZVSCARR_05M-CARRID .
ZTSCARR_05-CARRNAME =
ZVSCARR_05M-CARRNAME .
ZTSCARR_05-CURRCODE =
ZVSCARR_05M-CURRCODE .
ZTSCARR_05-URL =
ZVSCARR_05M-URL .
    IF SY-SUBRC = 0.
    UPDATE ZTSCARR_05 ##WARN_OK.
    ELSE.
    INSERT ZTSCARR_05 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSCARR_05M-UPD_FLAG,
STATUS_ZVSCARR_05M-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSCARR_05M.
  SELECT SINGLE * FROM ZTSCARR_05 WHERE
CARRID = ZVSCARR_05M-CARRID .
ZVSCARR_05M-MANDT =
ZTSCARR_05-MANDT .
ZVSCARR_05M-CARRID =
ZTSCARR_05-CARRID .
ZVSCARR_05M-CARRNAME =
ZTSCARR_05-CARRNAME .
ZVSCARR_05M-CURRCODE =
ZTSCARR_05-CURRCODE .
ZVSCARR_05M-URL =
ZTSCARR_05-URL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSCARR_05M USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSCARR_05M-CARRID TO
ZTSCARR_05-CARRID .
MOVE ZVSCARR_05M-MANDT TO
ZTSCARR_05-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSCARR_05'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSCARR_05 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSCARR_05'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVSPFLI_05M.....................................*
FORM GET_DATA_ZVSPFLI_05M.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSPFLI_05 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSPFLI_05M .
ZVSPFLI_05M-MANDT =
ZTSPFLI_05-MANDT .
ZVSPFLI_05M-CARRID =
ZTSPFLI_05-CARRID .
ZVSPFLI_05M-CONNID =
ZTSPFLI_05-CONNID .
ZVSPFLI_05M-COUNTRYFR =
ZTSPFLI_05-COUNTRYFR .
ZVSPFLI_05M-CITYFROM =
ZTSPFLI_05-CITYFROM .
ZVSPFLI_05M-AIRPFROM =
ZTSPFLI_05-AIRPFROM .
ZVSPFLI_05M-COUNTRYTO =
ZTSPFLI_05-COUNTRYTO .
ZVSPFLI_05M-CITYTO =
ZTSPFLI_05-CITYTO .
ZVSPFLI_05M-AIRPTO =
ZTSPFLI_05-AIRPTO .
ZVSPFLI_05M-FLTIME =
ZTSPFLI_05-FLTIME .
ZVSPFLI_05M-DEPTIME =
ZTSPFLI_05-DEPTIME .
ZVSPFLI_05M-ARRTIME =
ZTSPFLI_05-ARRTIME .
ZVSPFLI_05M-DISTANCE =
ZTSPFLI_05-DISTANCE .
ZVSPFLI_05M-DISTID =
ZTSPFLI_05-DISTID .
ZVSPFLI_05M-FLTYPE =
ZTSPFLI_05-FLTYPE .
ZVSPFLI_05M-PERIOD =
ZTSPFLI_05-PERIOD .
<VIM_TOTAL_STRUC> = ZVSPFLI_05M.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSPFLI_05M .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSPFLI_05M.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSPFLI_05M-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSPFLI_05 WHERE
  CARRID = ZVSPFLI_05M-CARRID AND
  CONNID = ZVSPFLI_05M-CONNID .
    IF SY-SUBRC = 0.
    DELETE ZTSPFLI_05 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSPFLI_05 WHERE
  CARRID = ZVSPFLI_05M-CARRID AND
  CONNID = ZVSPFLI_05M-CONNID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSPFLI_05.
    ENDIF.
ZTSPFLI_05-MANDT =
ZVSPFLI_05M-MANDT .
ZTSPFLI_05-CARRID =
ZVSPFLI_05M-CARRID .
ZTSPFLI_05-CONNID =
ZVSPFLI_05M-CONNID .
ZTSPFLI_05-COUNTRYFR =
ZVSPFLI_05M-COUNTRYFR .
ZTSPFLI_05-CITYFROM =
ZVSPFLI_05M-CITYFROM .
ZTSPFLI_05-AIRPFROM =
ZVSPFLI_05M-AIRPFROM .
ZTSPFLI_05-COUNTRYTO =
ZVSPFLI_05M-COUNTRYTO .
ZTSPFLI_05-CITYTO =
ZVSPFLI_05M-CITYTO .
ZTSPFLI_05-AIRPTO =
ZVSPFLI_05M-AIRPTO .
ZTSPFLI_05-FLTIME =
ZVSPFLI_05M-FLTIME .
ZTSPFLI_05-DEPTIME =
ZVSPFLI_05M-DEPTIME .
ZTSPFLI_05-ARRTIME =
ZVSPFLI_05M-ARRTIME .
ZTSPFLI_05-DISTANCE =
ZVSPFLI_05M-DISTANCE .
ZTSPFLI_05-DISTID =
ZVSPFLI_05M-DISTID .
ZTSPFLI_05-FLTYPE =
ZVSPFLI_05M-FLTYPE .
ZTSPFLI_05-PERIOD =
ZVSPFLI_05M-PERIOD .
    IF SY-SUBRC = 0.
    UPDATE ZTSPFLI_05 ##WARN_OK.
    ELSE.
    INSERT ZTSPFLI_05 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSPFLI_05M-UPD_FLAG,
STATUS_ZVSPFLI_05M-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSPFLI_05M.
  SELECT SINGLE * FROM ZTSPFLI_05 WHERE
CARRID = ZVSPFLI_05M-CARRID AND
CONNID = ZVSPFLI_05M-CONNID .
ZVSPFLI_05M-MANDT =
ZTSPFLI_05-MANDT .
ZVSPFLI_05M-CARRID =
ZTSPFLI_05-CARRID .
ZVSPFLI_05M-CONNID =
ZTSPFLI_05-CONNID .
ZVSPFLI_05M-COUNTRYFR =
ZTSPFLI_05-COUNTRYFR .
ZVSPFLI_05M-CITYFROM =
ZTSPFLI_05-CITYFROM .
ZVSPFLI_05M-AIRPFROM =
ZTSPFLI_05-AIRPFROM .
ZVSPFLI_05M-COUNTRYTO =
ZTSPFLI_05-COUNTRYTO .
ZVSPFLI_05M-CITYTO =
ZTSPFLI_05-CITYTO .
ZVSPFLI_05M-AIRPTO =
ZTSPFLI_05-AIRPTO .
ZVSPFLI_05M-FLTIME =
ZTSPFLI_05-FLTIME .
ZVSPFLI_05M-DEPTIME =
ZTSPFLI_05-DEPTIME .
ZVSPFLI_05M-ARRTIME =
ZTSPFLI_05-ARRTIME .
ZVSPFLI_05M-DISTANCE =
ZTSPFLI_05-DISTANCE .
ZVSPFLI_05M-DISTID =
ZTSPFLI_05-DISTID .
ZVSPFLI_05M-FLTYPE =
ZTSPFLI_05-FLTYPE .
ZVSPFLI_05M-PERIOD =
ZTSPFLI_05-PERIOD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSPFLI_05M USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSPFLI_05M-CARRID TO
ZTSPFLI_05-CARRID .
MOVE ZVSPFLI_05M-CONNID TO
ZTSPFLI_05-CONNID .
MOVE ZVSPFLI_05M-MANDT TO
ZTSPFLI_05-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSPFLI_05'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSPFLI_05 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSPFLI_05'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
