REPORT ZSUBRTN_PRC_PRG_05.
TYPES : TV_PERC TYPE P LENGTH 3 DECIMALS 2.
DATA : LV_RESULT TYPE TV_PERC.
PARAMETERS: PA_INT1 TYPE I,
            PA_INT2 TYPE I.

PERFORM CALC_PERC USING PA_INT1 CHANGING PA_INT2 LV_RESULT.
WRITE:/ '결과 : ', LV_RESULT, '%'.
WRITE:/ PA_INT1, PA_INT2.
form calc_perc  using    VALUE(PV_INT1) TYPE I"CALL BY VALUE"
                changing VALUE(PV_INT2) TYPE I"CALL BY VALUE AND RESULT"
                         PV_RESULT TYPE TV_PERC."CALL BY REFERENCE"
    PV_RESULT = PV_INT1 / PV_INT2 * 100."CALL BY REFERENCE니까 주소값에 찾아가서 바로 변경해줌(ex. 집에 찾아가서 집주인 바꿈)
    PV_INT1 = 100."CALL BY VALUE로 선언된 것이니까 원래의 값 PA_INT1을 변경시켜주진 않음)
    PV_INT2 = 100."CALL BY VALUE AND RESULT로 선언 되었으므로 SUBROUTINE이 끝나고 본래의 ROUTINE으로 돌아갔을 때 값을 변경해줌
*    CALL BY VALUE는 변화 X CALL BY VALUE AND RESULT는 FORM이 끝난 후 변화 O
    "CALL BY REFERENCE는 바로 변화(CALL BY REFERENCE는 USING에 써도 되고 CHANGING에 써도됨"
endform.
